from django.test import TestCase
from django.utils import timezone
from rest_framework.test import APIClient
from datetime import time, timedelta
from core.models import User, ClassRoom, Schedule, Session
from core.views import sync_daily_sessions

class SessionAutoSyncTest(TestCase):
    def setUp(self):
        self.instructor = User.objects.create_user(username='inst1', password='pwd', role=User.Role.INSTRUCTOR)
        self.classroom = ClassRoom.objects.create(name='Physics 101')
        self.classroom.instructors.add(self.instructor)

        self.today = timezone.localdate()
        self.weekday = self.today.weekday()

    def test_sync_daily_sessions_creates_session_for_today(self):
        # Create schedule for today
        schedule = Schedule.objects.create(
            classroom=self.classroom,
            day_of_week=self.weekday,
            start_time=time(10, 0),
            end_time=time(11, 30)
        )

        # Call sync
        sync_daily_sessions()

        # Session should exist for today
        session = Session.objects.filter(classroom=self.classroom, date=self.today).first()
        self.assertIsNotNone(session)
        self.assertEqual(session.schedule, schedule)

    def test_session_status_becomes_ready_during_class_time(self):
        now = timezone.localtime()
        # Schedule starting 5 minutes ago, ending in 45 minutes
        start_t = (now - timedelta(minutes=5)).time()
        end_t = (now + timedelta(minutes=45)).time()

        schedule = Schedule.objects.create(
            classroom=self.classroom,
            day_of_week=self.weekday,
            start_time=start_t,
            end_time=end_t
        )

        sync_daily_sessions()

        session = Session.objects.get(classroom=self.classroom, date=self.today)
        self.assertEqual(session.status, Session.Status.READY)

    def test_session_api_triggers_auto_sync(self):
        schedule = Schedule.objects.create(
            classroom=self.classroom,
            day_of_week=self.weekday,
            start_time=time(10, 0),
            end_time=time(11, 30)
        )

        client = APIClient()
        client.force_authenticate(user=self.instructor)

        response = client.get('/api/sessions/')
        self.assertEqual(response.status_code, 200)

        # Confirm session was generated by API call
        self.assertTrue(Session.objects.filter(classroom=self.classroom, date=self.today).exists())

