# Generated by Django 6.0.7 on 2026-08-03 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('user_role', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('AUTH', 'AUTH'), ('USER_MGMT', 'USER_MGMT'), ('CLASSROOM', 'CLASSROOM'), ('CONTENT', 'CONTENT'), ('SUBMISSION', 'SUBMISSION'), ('ATTENDANCE', 'ATTENDANCE'), ('SCHEDULE', 'SCHEDULE'), ('FORUM', 'FORUM')], max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('action_display', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='SUCCESS', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='activity_lo_categor_c9586c_idx'), models.Index(fields=['user_role'], name='activity_lo_user_ro_e6e4a6_idx'), models.Index(fields=['status'], name='activity_lo_status_78f2cb_idx'), models.Index(fields=['-created_at'], name='activity_lo_created_14fffc_idx')],
            },
        ),
    ]
