# Generated by Django 6.0 on 2026-08-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='category',
            field=models.CharField(choices=[('AUTH', 'AUTH'), ('USER_MGMT', 'USER_MGMT'), ('CLASSROOM', 'CLASSROOM'), ('CONTENT', 'CONTENT'), ('SUBMISSION', 'SUBMISSION'), ('ATTENDANCE', 'ATTENDANCE'), ('SCHEDULE', 'SCHEDULE'), ('FORUM', 'FORUM'), ('EXAM', 'EXAM')], max_length=20),
        ),
    ]
