# Generated by Django 6.0.7 on 2026-07-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role_exam_grade_parentstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/attachments/'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/submissions/'),
        ),
    ]
