# Generated by Django 6.0.7 on 2026-08-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_practiceexam_examsubjectscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_counselor',
            field=models.BooleanField(default=False),
        ),
    ]
