# Generated by Django 6.0.7 on 2026-07-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_assignment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=15),
        ),
    ]
